gpus: [0]

data:
  raw_directory: 'C:/Users/pps21/Documents/Cornell/data/NLST_nifti_60/'
  annotations_dir: 'C:/Users/pps21/Box/NLST Chest CT/Annotations - VT/'
  data_splits: 'C:/Users/pps21/Documents/Cornell/data/nnUNet-train_val-split.csv'
  batch_size_per_gpu: 2
  dataloader_workers_per_gpu: 1
  target_size: [ 256, 256, 256]
  num_classes: 1
#  crop_heart: False

logging:
  root_path: 't'
  name: 'best_nnUNet_split'
  train_logs_steps: 100

model:
  name: 'UNet'

train:
  epochs: 200
  grad_clip: 10.0
  precision: 32
  lr: 1.0e-4
  loss:
    name: 'BCEWithLogitsLoss'

  aug:
    name: 'basic3d'
