gpus: [0]

data:
  raw_directory: '/home/prs247/data/NLST_nifti/'
  annotations_dir: '/home/prs247/data/Annotations - VT/'
  data_splits: '/home/prs247/data/NLST-train_val_test-split-120.csv'
  batch_size_per_gpu: 1
  dataloader_workers_per_gpu: 16
  target_size: [ 256, 256, 256]
  num_classes: 1
#  crop_heart: False

logging:
  root_path: 't'
  name: 'best_nnUNet_split'
  train_logs_steps: 100

model:
  name: 'UNet'

train:
  epochs: 100
  grad_clip: 10.0
  precision: 32
  lr: 1.0e-4
  loss:
    name: 'BCEWithLogitsLoss'

  aug:
    name: 'basic3d'
